export const ND335_CATALOG = [
  { id: 'I.A.1', group: 'I.A. LÃNH Äáº O VÄN PHÃNG', name: 'Chá» Äáº¡o, Äiá»u hÃ nh thá»±c hiá»n nhiá»m vá»¥ chuyÃªn mÃ´n cá»§a VÄn phÃ²ng', output: 'Káº¿ hoáº¡ch cÃ´ng tÃ¡c (nÄm/quÃ½/thÃ¡ng); Káº¿t luáº­n chá» Äáº¡o; PhÃ¢n cÃ´ng nhiá»m vá»¥', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'I.A.2', group: 'I.A. LÃNH Äáº O VÄN PHÃNG', name: 'Xem xÃ©t, kÃ½ ban hÃ nh vÄn báº£n thuá»c tháº©m quyá»n', output: 'VÄn báº£n hÃ nh chÃ­nh ÄÃ£ kÃ½; Há» sÆ¡ trÃ¬nh; Phiáº¿u trÃ¬nh tháº©m Äá»nh', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'I.A.3', group: 'I.A. LÃNH Äáº O VÄN PHÃNG', name: 'Chá»§ trÃ¬ hoáº·c tham dá»± cÃ¡c cuá»c há»p, há»i nghá»', output: 'ThÃ´ng bÃ¡o káº¿t luáº­n; BiÃªn báº£n; Ã kiáº¿n phÃ¡t biá»u (vÄn báº£n)', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'I.A.4', group: 'I.A. LÃNH Äáº O VÄN PHÃNG', name: 'ÄÃ¡nh giÃ¡, nháº­n xÃ©t, xáº¿p loáº¡i cÃ´ng chá»©c, ngÆ°á»i lao Äá»ng', output: 'Phiáº¿u ÄÃ¡nh giÃ¡; Quyáº¿t Äá»nh/thÃ´ng bÃ¡o xáº¿p loáº¡i', level: 'N3', maxScore: 300, hasFactor: true },
  
  { id: 'I.B.1', group: 'I.B. LÃNH Äáº O Cáº¤P PHÃNG', name: 'Chá» Äáº¡o, Äiá»u hÃ nh nhiá»m vá»¥ chuyÃªn mÃ´n cá»§a phÃ²ng', output: 'Káº¿ hoáº¡ch cÃ´ng tÃ¡c phÃ²ng; PhÃ¢n cÃ´ng nhiá»m vá»¥ ná»i bá»', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'I.B.2', group: 'I.B. LÃNH Äáº O Cáº¤P PHÃNG', name: 'Xem xÃ©t, trÃ¬nh lÃ£nh Äáº¡o VÄn phÃ²ng kÃ½ vÄn báº£n', output: 'VÄn báº£n trÃ¬nh kÃ½; VÄn báº£n ÄÃ£ kÃ½ theo á»§y quyá»n', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'I.B.3', group: 'I.B. LÃNH Äáº O Cáº¤P PHÃNG', name: 'Chá»§ trÃ¬ cuá»c há»p ná»i bá» phÃ²ng', output: 'Káº¿t luáº­n há»p phÃ²ng; BiÃªn báº£n; Äá» xuáº¥t tá»ng há»£p', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'I.B.4', group: 'I.B. LÃNH Äáº O Cáº¤P PHÃNG', name: 'RÃ  soÃ¡t, kiá»m tra, hoÃ n thiá»n vÄn báº£n do chuyÃªn viÃªn dá»± tháº£o', output: 'VÄn báº£n ÄÃ£ hoÃ n thiá»n; Phiáº¿u kiá»m tra thá» thá»©c', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'I.B.5', group: 'I.B. LÃNH Äáº O Cáº¤P PHÃNG', name: 'Tá» chá»©c ÄÃ¡nh giÃ¡, xáº¿p loáº¡i cÃ´ng chá»©c phÃ²ng', output: 'Biá»u ÄÃ¡nh giÃ¡ thÃ¡ng/quÃ½; Tá»ng há»£p káº¿t quáº£ phÃ²ng', level: 'N2', maxScore: 200, hasFactor: true },
  
  { id: 'II.A.1', group: 'II.A. DÃNG CHUNG', name: 'Soáº¡n tháº£o vÄn báº£n hÃ nh chÃ­nh, chuyÃªn mÃ´n', output: 'CÃ´ng vÄn; Tá» trÃ¬nh; ThÃ´ng bÃ¡o; Giáº¥y má»i; BÃ¡o cÃ¡o Äá» xuáº¥t; Sao y', level: 'N1', maxScore: 100, hasFactor: true },
  { id: 'II.A.2', group: 'II.A. DÃNG CHUNG', name: 'XÃ¢y dá»±ng bÃ¡o cÃ¡o, chÆ°Æ¡ng trÃ¬nh, káº¿ hoáº¡ch cÃ´ng tÃ¡c', output: 'BÃ¡o cÃ¡o thÃ¡ng/quÃ½/nÄm; Káº¿ hoáº¡ch cÃ´ng tÃ¡c cÃ¡ nhÃ¢n/phÃ²ng', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.A.3', group: 'II.A. DÃNG CHUNG', name: 'Thá»±c hiá»n cÃ´ng tÃ¡c vÄn thÆ°, lÆ°u trá»¯', output: 'Sá» vÄn báº£n Äáº¿n/Äi; Há» sÆ¡ lÆ°u trá»¯; VÄn báº£n phÃ¡t hÃ nh', level: 'N1', maxScore: 100, hasFactor: true },
  { id: 'II.A.4', group: 'II.A. DÃNG CHUNG', name: 'Thá»±c hiá»n cÃ´ng tÃ¡c hÃ nh chÃ­nh, háº­u cáº§n', output: 'Lá»ch cÃ´ng tÃ¡c; Há» sÆ¡ ÄÄng kÃ½ xe, phÃ²ng há»p, lá» tÃ¢n', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.A.5', group: 'II.A. DÃNG CHUNG', name: 'Thá»±c hiá»n cÃ´ng tÃ¡c tÃ i chÃ­nh, káº¿ toÃ¡n', output: 'Dá»± toÃ¡n; Chá»©ng tá»«; BÃ¡o cÃ¡o quyáº¿t toÃ¡n; Há» sÆ¡ thanh toÃ¡n', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.A.6', group: 'II.A. DÃNG CHUNG', name: 'Tham mÆ°u á»©ng dá»¥ng CNTT, chuyá»n Äá»i sá»', output: 'Káº¿ hoáº¡ch CÄS; BÃ¡o cÃ¡o CNTT; TÃ i khoáº£n há» thá»ng', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.A.7', group: 'II.A. DÃNG CHUNG', name: 'Thá»±c hiá»n cÃ´ng tÃ¡c tá» chá»©c cÃ¡n bá», thi Äua khen thÆ°á»ng', output: 'Há» sÆ¡ cÃ¡n bá»; Há» sÆ¡ thi Äua; Quyáº¿t Äá»nh', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.A.8', group: 'II.A. DÃNG CHUNG', name: 'Thá»±c hiá»n nhiá»m vá»¥ khÃ¡c theo phÃ¢n cÃ´ng', output: 'VÄn báº£n tham mÆ°u; Káº¿t quáº£ thá»±c hiá»n', level: 'N2', maxScore: 200, hasFactor: true },

  { id: 'II.B.1', group: 'II.B. Äáº¶C THÃ', name: 'Tham mÆ°u, xÃ¢y dá»±ng chÆ°Æ¡ng trÃ¬nh, bÃ¡o cÃ¡o hoáº¡t Äá»ng chung cá»§a ÄoÃ n ÄBQH', output: 'ChÆ°Æ¡ng trÃ¬nh, káº¿ hoáº¡ch; BÃ¡o cÃ¡o Äá»nh ká»³', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.2', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ ÄBQH tham dá»± ká»³ há»p Quá»c há»i, UBTVQH', output: 'TÃ i liá»u tá»ng há»£p; BÃ¡o cÃ¡o gá»£i Ã½ tháº£o luáº­n; BiÃªn báº£n; BÃ¡o cÃ¡o nhanh', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.3', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ ÄBQH cháº¥t váº¥n táº¡i phiÃªn há»p UBTVQH', output: 'TÃ i liá»u; ChÆ°Æ¡ng trÃ¬nh; Ma-kÃ©t; CÃ´ng vÄn Äiá»u hÃ²a', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.4', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ ÄoÃ n ÄBQH tham gia xÃ¢y dá»±ng phÃ¡p luáº­t', output: 'VÄn báº£n gÃ³p Ã½ dá»± Ã¡n Luáº­t; BÃ¡o cÃ¡o tá»ng há»£p; Há» sÆ¡ há»i nghá»', level: 'N4', maxScore: 400, hasFactor: true },
  { id: 'II.B.5', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ giÃ¡m sÃ¡t, kháº£o sÃ¡t cá»§a ÄoÃ n ÄBQH', output: 'Káº¿ hoáº¡ch; Äá» cÆ°Æ¡ng; BÃ¡o cÃ¡o káº¿t quáº£; Káº¿t luáº­n/Kiáº¿n nghá»', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.6', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ ÄBQH tiáº¿p xÃºc cá»­ tri', output: 'Káº¿ hoáº¡ch; Lá»ch; TÃ i liá»u; BÃ¡o cÃ¡o tá»ng há»£p Ã½ kiáº¿n cá»­ tri', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.7', group: 'II.B. Äáº¶C THÃ', name: 'Theo dÃµi, ÄÃ´n Äá»c giáº£i quyáº¿t kiáº¿n nghá» cá»­ tri', output: 'BÃ¡o cÃ¡o tá»ng há»£p; VÄn báº£n chuyá»n/ÄÃ´n Äá»c', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.8', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ hoáº¡t Äá»ng chung cá»§a HÄND tá»nh', output: 'ChÆ°Æ¡ng trÃ¬nh cÃ´ng tÃ¡c; BÃ¡o cÃ¡o Äá»nh ká»³', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.9', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ ThÆ°á»ng trá»±c HÄND', output: 'ChÆ°Æ¡ng trÃ¬nh; TÃ i liá»u phiÃªn há»p; ThÃ´ng bÃ¡o káº¿t luáº­n', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.10', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ tá» chá»©c ká»³ há»p HÄND', output: 'Káº¿ hoáº¡ch; ChÆ°Æ¡ng trÃ¬nh; Ká»ch báº£n; TÃ i liá»u; BiÃªn báº£n; Há» sÆ¡ ká»³ há»p', level: 'N4', maxScore: 400, hasFactor: true },
  { id: 'II.B.11', group: 'II.B. Äáº¶C THÃ', name: 'Tham mÆ°u xÃ¢y dá»±ng chÆ°Æ¡ng trÃ¬nh, ná»i dung ká»³ há»p vÃ  dá»± tháº£o nghá» quyáº¿t', output: 'Dá»± kiáº¿n chÆ°Æ¡ng trÃ¬nh; Dá»± tháº£o nghá» quyáº¿t; Tá» trÃ¬nh', level: 'N4', maxScore: 400, hasFactor: true },
  { id: 'II.B.12', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ cÃ¡c Ban HÄND tá»nh', output: 'ChÆ°Æ¡ng trÃ¬nh cÃ´ng tÃ¡c Ban; TÃ i liá»u; BÃ¡o cÃ¡o tháº©m tra', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.13', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ giÃ¡m sÃ¡t chuyÃªn Äá»', output: 'Quyáº¿t Äá»nh; Káº¿ hoáº¡ch; Äá» cÆ°Æ¡ng; BÃ¡o cÃ¡o; Káº¿t luáº­n', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.14', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ kháº£o sÃ¡t', output: 'Quyáº¿t Äá»nh; Káº¿ hoáº¡ch; Äá» cÆ°Æ¡ng; BÃ¡o cÃ¡o; ThÃ´ng bÃ¡o', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.15', group: 'II.B. Äáº¶C THÃ', name: 'Theo dÃµi, ÄÃ´n Äá»c thá»±c hiá»n nghá» quyáº¿t, káº¿t luáº­n sau giÃ¡m sÃ¡t', output: 'Báº£ng theo dÃµi; VÄn báº£n ÄÃ´n Äá»c; BÃ¡o cÃ¡o káº¿t quáº£', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.16', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ cháº¥t váº¥n, giáº£i trÃ¬nh', output: 'Danh má»¥c váº¥n Äá»; TÃ i liá»u; BiÃªn báº£n; ThÃ´ng bÃ¡o', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.17', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ Äáº¡i biá»u HÄND tiáº¿p xÃºc cá»­ tri', output: 'Káº¿ hoáº¡ch; Lá»ch; TÃ i liá»u; BÃ¡o cÃ¡o tá»ng há»£p', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.18', group: 'II.B. Äáº¶C THÃ', name: 'Tá»ng há»£p Ã½ kiáº¿n, kiáº¿n nghá» cá»­ tri trÆ°á»c/sau ká»³ há»p', output: 'BÃ¡o cÃ¡o tá»ng há»£p; Phá»¥ lá»¥c phÃ¢n loáº¡i; VÄn báº£n chuyá»n', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.19', group: 'II.B. Äáº¶C THÃ', name: 'Theo dÃµi, ÄÃ´n Äá»c giáº£i quyáº¿t kiáº¿n nghá» cá»­ tri (HÄND)', output: 'Báº£ng theo dÃµi; BÃ¡o cÃ¡o káº¿t quáº£', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.20', group: 'II.B. Äáº¶C THÃ', name: 'Tham mÆ°u cÃ´ng tÃ¡c nhÃ¢n sá»± thuá»c tháº©m quyá»n HÄND', output: 'Há» sÆ¡ tháº©m Äá»nh; Tá» trÃ¬nh; Nghá» quyáº¿t phÃª chuáº©n', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.21', group: 'II.B. Äáº¶C THÃ', name: 'Tiáº¿p cÃ´ng dÃ¢n cá»§a ÄBQH vÃ  ÄB HÄND', output: 'Lá»ch tiáº¿p cÃ´ng dÃ¢n; TÃ i liá»u phá»¥c vá»¥', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.22', group: 'II.B. Äáº¶C THÃ', name: 'Tiáº¿p nháº­n, phÃ¢n loáº¡i, xá»­ lÃ½ ÄÆ¡n thÆ°', output: 'Há» sÆ¡ xá»­ lÃ½ ÄÆ¡n; Phiáº¿u chuyá»n; VÄn báº£n ÄÃ´n Äá»c', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.23', group: 'II.B. Äáº¶C THÃ', name: 'Tham mÆ°u bÃ¡o cÃ¡o cÃ´ng tÃ¡c dÃ¢n nguyá»n', output: 'BÃ¡o cÃ¡o dÃ¢n nguyá»n tuáº§n/thÃ¡ng/quÃ½/nÄm', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.24', group: 'II.B. Äáº¶C THÃ', name: 'Tham mÆ°u thÃ´ng tin, tuyÃªn truyá»n', output: 'Tin, bÃ i, áº£nh; Káº¿ hoáº¡ch tuyÃªn truyá»n; ChuyÃªn má»¥c', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.25', group: 'II.B. Äáº¶C THÃ', name: 'Quáº£n lÃ½ Cá»ng TTÄT vÃ  pháº§n má»m phá»¥c vá»¥ ká»³ há»p', output: 'Dá»¯ liá»u cáº­p nháº­t; TÃ i liá»u Äiá»n tá»­; BÃ¡o cÃ¡o váº­n hÃ nh', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.26', group: 'II.B. Äáº¶C THÃ', name: 'Báº£o Äáº£m háº­u cáº§n, ká»¹ thuáº­t phá»¥c vá»¥ ká»³ há»p, há»i nghá», giÃ¡m sÃ¡t', output: 'Káº¿ hoáº¡ch phá»¥c vá»¥; PhÆ°Æ¡ng Ã¡n háº­u cáº§n; Há» sÆ¡ ÄoÃ n', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.27', group: 'II.B. Äáº¶C THÃ', name: 'Quáº£n lÃ½ tÃ i sáº£n, trang thiáº¿t bá»', output: 'Káº¿ hoáº¡ch mua sáº¯m; Há»£p Äá»ng; Sá» theo dÃµi tÃ i sáº£n', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.28', group: 'II.B. Äáº¶C THÃ', name: 'Thá»±c hiá»n cháº¿ Äá», chÃ­nh sÃ¡ch Äá»i vá»i ÄBQH, ÄB HÄND', output: 'Há» sÆ¡ cháº¿ Äá»; Danh sÃ¡ch chi tráº£; Há» sÆ¡ thanh toÃ¡n', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.29', group: 'II.B. Äáº¶C THÃ', name: 'Quáº£n lÃ½ há» sÆ¡, tÃ i liá»u ká»³ há»p, nghá» quyáº¿t, giÃ¡m sÃ¡t, TXCT', output: 'Há» sÆ¡ ká»³ há»p; Táº­p nghá» quyáº¿t; BiÃªn báº£n; Danh má»¥c lÆ°u trá»¯', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.30', group: 'II.B. Äáº¶C THÃ', name: 'Tá»ng há»£p bÃ¡o cÃ¡o cÃ´ng tÃ¡c', output: 'BÃ¡o cÃ¡o thÃ¡ng/quÃ½/nÄm; Phá»¥ lá»¥c sá» liá»u', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.31', group: 'II.B. Äáº¶C THÃ', name: 'Phá»i há»£p cÃ´ng tÃ¡c vá»i cÃ¡c sá», ban, ngÃ nh, Äá»a phÆ°Æ¡ng', output: 'VÄn báº£n phá»i há»£p; BÃ¡o cÃ¡o káº¿t quáº£ phá»i há»£p', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.32', group: 'II.B. Äáº¶C THÃ', name: 'Phá»¥c vá»¥ hoáº¡t Äá»ng Äá»i ngoáº¡i, trao Äá»i kinh nghiá»m', output: 'Káº¿ hoáº¡ch; ChÆ°Æ¡ng trÃ¬nh; TÃ i liá»u táº­p huáº¥n; BÃ¡o cÃ¡o', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.33', group: 'II.B. Äáº¶C THÃ', name: 'Tham mÆ°u cáº£i cÃ¡ch hÃ nh chÃ­nh, chuyá»n Äá»i sá»', output: 'Káº¿ hoáº¡ch CCHC/CÄS; BÃ¡o cÃ¡o ÄÃ¡nh giÃ¡; Quy trÃ¬nh Äiá»n tá»­', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.34', group: 'II.B. Äáº¶C THÃ', name: 'XÃ¢y dá»±ng, rÃ  soÃ¡t quy cháº¿, quy Äá»nh, quy trÃ¬nh ná»i bá»', output: 'Quy cháº¿; Quy Äá»nh; Quy trÃ¬nh; HÆ°á»ng dáº«n ná»i bá»', level: 'N3', maxScore: 300, hasFactor: true },

  { id: 'III.1', group: 'III. Há» TRá»¢, PHá»¤C Vá»¤', name: 'LÃ¡i xe; báº£o quáº£n, váº­n hÃ nh, báº£o dÆ°á»¡ng phÆ°Æ¡ng tiá»n', output: 'Nháº­t kÃ½ hÃ nh trÃ¬nh; Nháº­t kÃ½ báº£o dÆ°á»¡ng; BiÃªn báº£n bÃ n giao', level: 'Há» trá»£', maxScore: 0, hasFactor: false },
  { id: 'III.2', group: 'III. Há» TRá»¢, PHá»¤C Vá»¤', name: 'Báº£o vá» an ninh tráº­t tá»±; kiá»m soÃ¡t ra vÃ o; PCCC', output: 'Nháº­t kÃ½ ca trá»±c; BiÃªn báº£n sá»± cá»; Sá» trá»±c báº£o vá»', level: 'Há» trá»£', maxScore: 0, hasFactor: false },
  { id: 'III.3', group: 'III. Há» TRá»¢, PHá»¤C Vá»¤', name: 'Vá» sinh cÆ¡ quan, phÃ²ng lÃ m viá»c; phá»¥c vá»¥ há»i nghá», tiáº¿p khÃ¡ch', output: 'Nháº­t kÃ½ vá» sinh; BÃ¡o cÃ¡o phá»¥c vá»¥ há»i nghá»', level: 'Há» trá»£', maxScore: 0, hasFactor: false },
  { id: 'III.4', group: 'III. Há» TRá»¢, PHá»¤C Vá»¤', name: 'Báº£o trÃ¬, váº­n hÃ nh, sá»­a chá»¯a thiáº¿t bá», phÆ°Æ¡ng tiá»n ká»¹ thuáº­t', output: 'BiÃªn báº£n bÃ n giao sá»­a chá»¯a; BiÃªn báº£n nghiá»m thu; Nháº­t kÃ½ váº­n hÃ nh', level: 'Há» trá»£', maxScore: 0, hasFactor: false },
];

export const CRITERIA_335 = [
  { id: '1', name: 'Phẩm chất chính trị, phẩm chất đạo đức, văn hóa thực thi công vụ', maxScore: 5 },
  { id: '2', name: 'Ý thức kỷ luật, kỷ cương trong thực thi công vụ', maxScore: 5 },
  { id: '3', name: 'Năng lực chuyên môn, nghiệp vụ theo yêu cầu của vị trí việc làm', maxScore: 2.5 },
  { id: '4', name: 'Khả năng đáp ứng yêu cầu thực thi nhiệm vụ được giao thường xuyên, đột xuất', maxScore: 2.5 },
  { id: '5', name: 'Tinh thần trách nhiệm trong thực thi công vụ', maxScore: 2.5 },
  { id: '6', name: 'Thái độ phục vụ người dân, doanh nghiệp và khả năng phối hợp', maxScore: 2.5 },
  { id: '7', name: 'Có sản phẩm, giải pháp đột phá, sáng tạo đem lại giá trị, hiệu quả thiết thực', maxScore: 2.5 },
  { id: '8', name: 'Sẵn sàng tham gia thực hiện nhiệm vụ chính trị đặc biệt quan trọng, đột xuất', maxScore: 2.5 },
  { id: '9', name: 'Có tinh thần chịu trách nhiệm trước kết quả công việc; chủ động nhận lỗi', maxScore: 2.5 },
  { id: '10', name: 'Chủ động đưa ra quyết định trong phạm vi thẩm quyền, không né tránh', maxScore: 2.5 }
];
