export const ND335_CATALOG = [
  { id: 'I.A.1', group: 'I.A. LÃNH ĐẠO VĂN PHÒNG', name: 'Chỉ đạo, điều hành thực hiện nhiệm vụ chuyên môn của Văn phòng', output: 'Kế hoạch công tác (năm/quý/tháng); Kết luận chỉ đạo; Phân công nhiệm vụ', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'I.A.2', group: 'I.A. LÃNH ĐẠO VĂN PHÒNG', name: 'Xem xét, ký ban hành văn bản thuộc thẩm quyền', output: 'Văn bản hành chính đã ký; Hồ sơ trình; Phiếu trình thẩm định', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'I.A.3', group: 'I.A. LÃNH ĐẠO VĂN PHÒNG', name: 'Chủ trì hoặc tham dự các cuộc họp, hội nghị', output: 'Thông báo kết luận; Biên bản; Ý kiến phát biểu (văn bản)', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'I.A.4', group: 'I.A. LÃNH ĐẠO VĂN PHÒNG', name: 'Đánh giá, nhận xét, xếp loại công chức, người lao động', output: 'Phiếu đánh giá; Quyết định/thông báo xếp loại', level: 'N3', maxScore: 300, hasFactor: true },
  
  { id: 'I.B.1', group: 'I.B. LÃNH ĐẠO CẤP PHÒNG', name: 'Chỉ đạo, điều hành nhiệm vụ chuyên môn của phòng', output: 'Kế hoạch công tác phòng; Phân công nhiệm vụ nội bộ', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'I.B.2', group: 'I.B. LÃNH ĐẠO CẤP PHÒNG', name: 'Xem xét, trình lãnh đạo Văn phòng ký văn bản', output: 'Văn bản trình ký; Văn bản đã ký theo ủy quyền', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'I.B.3', group: 'I.B. LÃNH ĐẠO CẤP PHÒNG', name: 'Chủ trì cuộc họp nội bộ phòng', output: 'Kết luận họp phòng; Biên bản; Đề xuất tổng hợp', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'I.B.4', group: 'I.B. LÃNH ĐẠO CẤP PHÒNG', name: 'Rà soát, kiểm tra, hoàn thiện văn bản do chuyên viên dự thảo', output: 'Văn bản đã hoàn thiện; Phiếu kiểm tra thể thức', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'I.B.5', group: 'I.B. LÃNH ĐẠO CẤP PHÒNG', name: 'Tổ chức đánh giá, xếp loại công chức phòng', output: 'Biểu đánh giá tháng/quý; Tổng hợp kết quả phòng', level: 'N2', maxScore: 200, hasFactor: true },
  
  { id: 'II.A.1', group: 'II.A. DÙNG CHUNG', name: 'Soạn thảo văn bản hành chính, chuyên môn', output: 'Công văn; Tờ trình; Thông báo; Giấy mời; Báo cáo đề xuất; Sao y', level: 'N1', maxScore: 100, hasFactor: true },
  { id: 'II.A.2', group: 'II.A. DÙNG CHUNG', name: 'Xây dựng báo cáo, chương trình, kế hoạch công tác', output: 'Báo cáo tháng/quý/năm; Kế hoạch công tác cá nhân/phòng', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.A.3', group: 'II.A. DÙNG CHUNG', name: 'Thực hiện công tác văn thư, lưu trữ', output: 'Sổ văn bản đến/đi; Hồ sơ lưu trữ; Văn bản phát hành', level: 'N1', maxScore: 100, hasFactor: true },
  { id: 'II.A.4', group: 'II.A. DÙNG CHUNG', name: 'Thực hiện công tác hành chính, hậu cần', output: 'Lịch công tác; Hồ sơ đăng ký xe, phòng họp, lễ tân', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.A.5', group: 'II.A. DÙNG CHUNG', name: 'Thực hiện công tác tài chính, kế toán', output: 'Dự toán; Chứng từ; Báo cáo quyết toán; Hồ sơ thanh toán', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.A.6', group: 'II.A. DÙNG CHUNG', name: 'Tham mưu ứng dụng CNTT, chuyển đổi số', output: 'Kế hoạch CĐS; Báo cáo CNTT; Tài khoản hệ thống', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.A.7', group: 'II.A. DÙNG CHUNG', name: 'Thực hiện công tác tổ chức cán bộ, thi đua khen thưởng', output: 'Hồ sơ cán bộ; Hồ sơ thi đua; Quyết định', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.A.8', group: 'II.A. DÙNG CHUNG', name: 'Thực hiện nhiệm vụ khác theo phân công', output: 'Văn bản tham mưu; Kết quả thực hiện', level: 'N2', maxScore: 200, hasFactor: true },

  { id: 'II.B.1', group: 'II.B. ĐẶC THÙ', name: 'Tham mưu, xây dựng chương trình, báo cáo hoạt động chung của Đoàn ĐBQH', output: 'Chương trình, kế hoạch; Báo cáo định kỳ', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.2', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ ĐBQH tham dự kỳ họp Quốc hội, UBTVQH', output: 'Tài liệu tổng hợp; Báo cáo gợi ý thảo luận; Biên bản; Báo cáo nhanh', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.3', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ ĐBQH chất vấn tại phiên họp UBTVQH', output: 'Tài liệu; Chương trình; Ma-két; Công văn điều hòa', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.4', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ Đoàn ĐBQH tham gia xây dựng pháp luật', output: 'Văn bản góp ý dự án Luật; Báo cáo tổng hợp; Hồ sơ hội nghị', level: 'N4', maxScore: 400, hasFactor: true },
  { id: 'II.B.5', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ giám sát, khảo sát của Đoàn ĐBQH', output: 'Kế hoạch; Đề cương; Báo cáo kết quả; Kết luận/Kiến nghị', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.6', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ ĐBQH tiếp xúc cử tri', output: 'Kế hoạch; Lịch; Tài liệu; Báo cáo tổng hợp ý kiến cử tri', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.7', group: 'II.B. ĐẶC THÙ', name: 'Theo dõi, đôn đốc giải quyết kiến nghị cử tri', output: 'Báo cáo tổng hợp; Văn bản chuyển/đôn đốc', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.8', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ hoạt động chung của HĐND tỉnh', output: 'Chương trình công tác; Báo cáo định kỳ', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.9', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ Thường trực HĐND', output: 'Chương trình; Tài liệu phiên họp; Thông báo kết luận', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.10', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ tổ chức kỳ họp HĐND', output: 'Kế hoạch; Chương trình; Kịch bản; Tài liệu; Biên bản; Hồ sơ kỳ họp', level: 'N4', maxScore: 400, hasFactor: true },
  { id: 'II.B.11', group: 'II.B. ĐẶC THÙ', name: 'Tham mưu xây dựng chương trình, nội dung kỳ họp và dự thảo nghị quyết', output: 'Dự kiến chương trình; Dự thảo nghị quyết; Tờ trình', level: 'N4', maxScore: 400, hasFactor: true },
  { id: 'II.B.12', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ các Ban HĐND tỉnh', output: 'Chương trình công tác Ban; Tài liệu; Báo cáo thẩm tra', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.13', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ giám sát chuyên đề', output: 'Quyết định; Kế hoạch; Đề cương; Báo cáo; Kết luận', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.14', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ khảo sát', output: 'Quyết định; Kế hoạch; Đề cương; Báo cáo; Thông báo', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.15', group: 'II.B. ĐẶC THÙ', name: 'Theo dõi, đôn đốc thực hiện nghị quyết, kết luận sau giám sát', output: 'Bảng theo dõi; Văn bản đôn đốc; Báo cáo kết quả', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.16', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ chất vấn, giải trình', output: 'Danh mục vấn đề; Tài liệu; Biên bản; Thông báo', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.17', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ đại biểu HĐND tiếp xúc cử tri', output: 'Kế hoạch; Lịch; Tài liệu; Báo cáo tổng hợp', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.18', group: 'II.B. ĐẶC THÙ', name: 'Tổng hợp ý kiến, kiến nghị cử tri trước/sau kỳ họp', output: 'Báo cáo tổng hợp; Phụ lục phân loại; Văn bản chuyển', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.19', group: 'II.B. ĐẶC THÙ', name: 'Theo dõi, đôn đốc giải quyết kiến nghị cử tri (HĐND)', output: 'Bảng theo dõi; Báo cáo kết quả', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.20', group: 'II.B. ĐẶC THÙ', name: 'Tham mưu công tác nhân sự thuộc thẩm quyền HĐND', output: 'Hồ sơ thẩm định; Tờ trình; Nghị quyết phê chuẩn', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.21', group: 'II.B. ĐẶC THÙ', name: 'Tiếp công dân của ĐBQH và ĐB HĐND', output: 'Lịch tiếp công dân; Tài liệu phục vụ', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.22', group: 'II.B. ĐẶC THÙ', name: 'Tiếp nhận, phân loại, xử lý đơn thư', output: 'Hồ sơ xử lý đơn; Phiếu chuyển; Văn bản đôn đốc', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.23', group: 'II.B. ĐẶC THÙ', name: 'Tham mưu báo cáo công tác dân nguyện', output: 'Báo cáo dân nguyện tuần/tháng/quý/năm', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.24', group: 'II.B. ĐẶC THÙ', name: 'Tham mưu thông tin, tuyên truyền', output: 'Tin, bài, ảnh; Kế hoạch tuyên truyền; Chuyên mục', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.25', group: 'II.B. ĐẶC THÙ', name: 'Quản lý Cổng TTĐT và phần mềm phục vụ kỳ họp', output: 'Dữ liệu cập nhật; Tài liệu điện tử; Báo cáo vận hành', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.26', group: 'II.B. ĐẶC THÙ', name: 'Bảo đảm hậu cần, kỹ thuật phục vụ kỳ họp, hội nghị, giám sát', output: 'Kế hoạch phục vụ; Phương án hậu cần; Hồ sơ đoàn', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.27', group: 'II.B. ĐẶC THÙ', name: 'Quản lý tài sản, trang thiết bị', output: 'Kế hoạch mua sắm; Hợp đồng; Sổ theo dõi tài sản', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.28', group: 'II.B. ĐẶC THÙ', name: 'Thực hiện chế độ, chính sách đối với ĐBQH, ĐB HĐND', output: 'Hồ sơ chế độ; Danh sách chi trả; Hồ sơ thanh toán', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.29', group: 'II.B. ĐẶC THÙ', name: 'Quản lý hồ sơ, tài liệu kỳ họp, nghị quyết, giám sát, TXCT', output: 'Hồ sơ kỳ họp; Tập nghị quyết; Biên bản; Danh mục lưu trữ', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.30', group: 'II.B. ĐẶC THÙ', name: 'Tổng hợp báo cáo công tác', output: 'Báo cáo tháng/quý/năm; Phụ lục số liệu', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.31', group: 'II.B. ĐẶC THÙ', name: 'Phối hợp công tác với các sở, ban, ngành, địa phương', output: 'Văn bản phối hợp; Báo cáo kết quả phối hợp', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.32', group: 'II.B. ĐẶC THÙ', name: 'Phục vụ hoạt động đối ngoại, trao đổi kinh nghiệm', output: 'Kế hoạch; Chương trình; Tài liệu tập huấn; Báo cáo', level: 'N2', maxScore: 200, hasFactor: true },
  { id: 'II.B.33', group: 'II.B. ĐẶC THÙ', name: 'Tham mưu cải cách hành chính, chuyển đổi số', output: 'Kế hoạch CCHC/CĐS; Báo cáo đánh giá; Quy trình điện tử', level: 'N3', maxScore: 300, hasFactor: true },
  { id: 'II.B.34', group: 'II.B. ĐẶC THÙ', name: 'Xây dựng, rà soát quy chế, quy định, quy trình nội bộ', output: 'Quy chế; Quy định; Quy trình; Hướng dẫn nội bộ', level: 'N3', maxScore: 300, hasFactor: true },

  { id: 'III.1', group: 'III. HỖ TRỢ, PHỤC VỤ', name: 'Lái xe; bảo quản, vận hành, bảo dưỡng phương tiện', output: 'Nhật ký hành trình; Nhật ký bảo dưỡng; Biên bản bàn giao', level: 'Hỗ trợ', maxScore: 0, hasFactor: false },
  { id: 'III.2', group: 'III. HỖ TRỢ, PHỤC VỤ', name: 'Bảo vệ an ninh trật tự; kiểm soát ra vào; PCCC', output: 'Nhật ký ca trực; Biên bản sự cố; Sổ trực bảo vệ', level: 'Hỗ trợ', maxScore: 0, hasFactor: false },
  { id: 'III.3', group: 'III. HỖ TRỢ, PHỤC VỤ', name: 'Vệ sinh cơ quan, phòng làm việc; phục vụ hội nghị, tiếp khách', output: 'Nhật ký vệ sinh; Báo cáo phục vụ hội nghị', level: 'Hỗ trợ', maxScore: 0, hasFactor: false },
  { id: 'III.4', group: 'III. HỖ TRỢ, PHỤC VỤ', name: 'Bảo trì, vận hành, sửa chữa thiết bị, phương tiện kỹ thuật', output: 'Biên bản bàn giao sửa chữa; Biên bản nghiệm thu; Nhật ký vận hành', level: 'Hỗ trợ', maxScore: 0, hasFactor: false },
];

export const CRITERIA_335 = [
  { id: '1', name: 'Phẩm chất chính trị, phẩm chất đạo đức, văn hóa thực thi công vụ', maxScore: 5 },
  { id: '2', name: 'Ý thức kỷ luật, kỷ cương trong thực thi công vụ', maxScore: 5 },
  { id: '3', name: 'Năng lực chuyên môn, nghiệp vụ theo yêu cầu của vị trí việc làm', maxScore: 2.5 },
  { id: '4', name: 'Khả năng đáp ứng yêu cầu thực thi nhiệm vụ được giao thường xuyên, đột xuất', maxScore: 2.5 },
  { id: '5', name: 'Tinh thần trách nhiệm trong thực thi công vụ', maxScore: 2.5 },
  { id: '6', name: 'Thái độ phục vụ người dân, doanh nghiệp và khả năng phối hợp', maxScore: 2.5 },
  { id: '7', name: 'Có sản phẩm, giải pháp đột phá, sáng tạo đem lại giá trị, hiệu quả thiết thực', maxScore: 2.5 },
  { id: '8', name: 'Sẵn sàng tham gia thực hiện nhiệm vụ chính trị đặc biệt quan trọng, đột xuất', maxScore: 2.5 },
  { id: '9', name: 'Có tinh thần chịu trách nhiệm trước kết quả công việc; chủ động nhận lỗi', maxScore: 2.5 },
  { id: '10', name: 'Chủ động đưa ra quyết định trong phạm vi thẩm quyền, không né tránh', maxScore: 2.5 }
];
